apiVersion: v1
kind: Pod
metadata:
  name: netperf-server
  annotations:
    kubernetes.io/egress-bandwidth: 1M
    kubernetes.io/ingress-bandwidth: 1M
spec:
  containers:
  - image: sirot/netperf-latest
    command: ["/bin/sh","-c","netserver -p 4444 -4; iperf3 -s -i 1;"]
    imagePullPolicy: IfNotPresent
    name: netperf
    ports:
    - name: netperf-port
      containerPort: 4444
    - name: iperf-port
      containerPort: 5210
  restartPolicy: Always


