# permissions for end users to view hffdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hffdemo-viewer-role
rules:
- apiGroups:
  - hffapp.fangfenghuang.io
  resources:
  - hffdemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hffapp.fangfenghuang.io
  resources:
  - hffdemoes/status
  verbs:
  - get
