---
apiVersion: v1
kind: Pod
metadata:
  name: test-kata
spec:
  nodeName: telecom-k8s-phy01
  runtimeClassName: kata-containers
  containers:
  - name: fio
    image: docker.io/xridge/fio:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /test
      name: test-volume
    command:
    - sleep
    - "999d"
    resources:
      limits:
        memory: "5Gi"
        cpu: "5"
  volumes:
  - name: test-volume
    hostPath:
      path: /hff/test/kata
      type: Directory

---
apiVersion: v1
kind: Pod
metadata:
  name: test-runc
spec:
  nodeName: telecom-k8s-phy01
  containers:
  - name: fio
    image: docker.io/xridge/fio:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /test
      name: test-volume
    command:
    - sleep
    - "999d"
    resources:
      limits:
        memory: "5Gi"
        cpu: "5"
  volumes:
  - name: test-volume
    hostPath:
      path: /hff/test/runc
      type: Directory

---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-server
spec:
  containers:
  - image: sirot/netperf-latest
    command: ["/bin/sh","-c","netserver -p 4444 -4; iperf3 -s -i 1;"]
    imagePullPolicy: IfNotPresent
    name: netperf
    ports:
    - name: netperf-port
    containerPort: 4444
    - name: iperf-port
    containerPort: 5210
