FROM sirot/netperf-latest

RUN wget http://brick.kernel.dk/snaps/fio-2.2.10.tar.gz --no-check-certificate \
    && tar -zxvf fio-2.2.10.tar.gz

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty main restricted universe multiverse" >/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-security main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-updates main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-proposed main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-backports main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty-security main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty-updates main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty-proposed main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty-backports main restricted universe multiverse" >>/etc/apt/sources.list


RUN apt-get update \
    && apt-get install libaio-dev -y --allow-unauthenticated \
    && apt-get install gcc -y --allow-unauthenticated \
    && apt-get install wget -y --allow-unauthenticated

RUN apt-get install pkg-config -y --allow-unauthenticated \
    && apt-get install gir1.2-pango-1.0  libgtk2.0-0 libspice-client-glib-2.0-dev -y --allow-unauthenticated \
    && apt-get install gtk+-2.0 -y --allow-unauthenticated

RUN  cd fio-2.2.10 \
    && ./configure --enable-gfio \
    && make fio \
    && make gfio \
    && make install \
    && rm -rf fio-2.2.10.tar.gz \
    && ln -s /usr/local/bin/fio /usr/bin/fio \
    && ln -s /usr/local/bin/gfio /usr/bin/gfio 

CMD ["fio", "-S"]




# docker build -f Dockerfile-iperf-fio-gfio -t hff-iperf-fio-gfio:v0.1 .

# ctr -n k8s.io run  -t --rm hff-iperf-fio-gfio:v0.1 hfftest sh

# gfio



./configure: 1051: ./configure: pkg-config: not found
./configure: 1058: ./configure: pkg-config: not found
configure: gtk and gthread not found
The command '/bin/sh -c cd fio-2.2.10     && ./configure --enable-gfio     && make fio     && make gfio     && make install     && rm -rf fio-2.2.10.tar.gz     && ln -s /usr/local/bin/fio /usr/bin/fio     && ln -s /usr/local/bin/gfio /usr/bin/gfio' returned a non-zero code: 1
