FROM sirot/netperf-latest

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty main restricted universe multiverse" >/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-security main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-updates main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-proposed main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-backports main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty-security main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty-updates main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty-proposed main restricted universe multiverse" >>/etc/apt/sources.list  && \
    echo "deb-src http://mirrors.aliyun.com/ubuntu/ trusty-backports main restricted universe multiverse" >>/etc/apt/sources.list


RUN apt-get update \
    && apt-get install libaio-dev -y --allow-unauthenticated \
    && apt-get install gcc -y --allow-unauthenticated \
    && apt-get install wget -y --allow-unauthenticated

RUN wget http://brick.kernel.dk/snaps/fio-2.2.10.tar.gz --no-check-certificate \
    && tar -zxvf fio-2.2.10.tar.gz

RUN  cd fio-2.2.10 \
    && cd fio-3.30 \
    && ./configure \
    && make \
    && make install \
    && rm -rf fio-2.2.10.tar.gz

CMD  ["/bin/sh","-c","netserver -p 4444 -4; iperf3 -s -i 1;"]

# docker build -t hff-fio-iperf:v0.1 .
