apiVersion: hffapp.fangfenghuang.io/v1
kind: HffDemo
metadata:
  name: hffdemo-sample
spec:
  unit: |-
    [Unit]
    Description=sample-test

    [Service]
    ExecStart=/opt/systemd-unit/sample-test.service -listen-address 0.0.0.0:80
    Restart=always
    StartLimitInterval=0
    RestartSec=10

    [Install]
    WantedBy=multi-user.target
  url: http://localhost:40080/test-package.tar
