apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-demo-svc
spec:
  ports:
  - port: 443
    targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-demo-deployment
  labels:
    app: admission-webhook-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook-demo
  template:
    metadata:
      labels:
        app: admission-webhook-demo
    spec:
      containers:
        - name: admission-webhook-demo
          image: hff/webhook-demo:v0.0.0
          imagePullPolicy: IfNotPresent
          args:
            - webhook-demo
            - -tlsCertPath=/etc/webhook/certs/cert.pem
            - -tlsKeyPath=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-demo-certs
