apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-demo-cfg
  labels:
    app: admission-webhook-demo
webhooks:
  - name: mutating-webhook-demo.hff.com
    clientConfig:
      service:
        name: admission-webhook-demo-svc
        namespace: default
        path: "/mutating"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook-demo-cfg
  labels:
    app: admission-webhook-demo
webhooks:
  - name: validation-webhook-demo.hff.com
    clientConfig:
      service:
        name: admission-webhook-demo-svc
        namespace: default
        path: "/validating"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
