{
 "title": "Kata containers",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Kata monitor", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "scrape count/60s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kata_monitor_scrape_count[5m])*60"
    }
   ]
  },
  {
   "title": "failed scrape count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_monitor_scrape_failed_count"
    }
   ]
  },
  {
   "title": "Running shims",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_monitor_running_shim_count"
    }
   ]
  },
  {
   "title": "scrape p99/avg (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kata_monitor_scrape_durations_histogram_milliseconds_bucket[5m])) by (action,le))",
     "legendFormat": "p99"
    },
    {
     "expr": "rate(kata_monitor_scrape_durations_histogram_milliseconds_sum[5m])/rate(kata_monitor_scrape_durations_histogram_milliseconds_count[5m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_monitor_go_goroutines" },
    { "expr": "kata_monitor_go_threads" }
   ]
  },
  {
   "title": "process_open_fds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_monitor_process_open_fds" }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_monitor_process_resident_memory_bytes"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kata_monitor_go_gc_duration_seconds_sum[5m])/rate(kata_monitor_go_gc_duration_seconds_count[5m])"
    }
   ]
  },
  { "title": "Kata shim", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CRI RPC p99/p95/p90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kata_shim_rpc_durations_histogram_milliseconds_bucket[5m])) by (action,le))"
    }
   ]
  },
  {
   "title": "Agent RPC p99/p95/p90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kata_shim_agent_rpc_durations_histogram_milliseconds_bucket [5m])) by (action,le))",
     "legendFormat": "p99/{{action}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kata_shim_agent_rpc_durations_histogram_milliseconds_bucket [5m])) by (action,le))",
     "legendFormat": "p95/{{action}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kata_shim_agent_rpc_durations_histogram_milliseconds_bucket [5m])) by (action,le))",
     "legendFormat": "p90/{{action}}"
    }
   ]
  },
  {
   "title": "Agent TOP RPC p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kata_shim_agent_rpc_durations_histogram_milliseconds_bucket{action=~\"grpc.GetMetricsRequest|grpc.CreateContainerRequest|grpc.CreateContainerRequest\"} [5m])) by (action,le))",
     "legendFormat": "p99/{{action}}"
    }
   ]
  },
  {
   "title": "Agent getMetrics RPC p99/p95/p90/avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kata_shim_agent_rpc_durations_histogram_milliseconds_bucket{action=\"grpc.GetMetricsRequest\"} [5m])) by (action,le))",
     "legendFormat": "p99/{{action}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kata_shim_agent_rpc_durations_histogram_milliseconds_bucket{action=\"grpc.GetMetricsRequest\"} [5m])) by (action,le))",
     "legendFormat": "p95/{{action}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kata_shim_agent_rpc_durations_histogram_milliseconds_bucket{action=\"grpc.GetMetricsRequest\"} [5m])) by (action,le))",
     "legendFormat": "p90/{{action}}"
    },
    {
     "expr": "rate(kata_shim_agent_rpc_durations_histogram_milliseconds_sum{action=\"grpc.GetMetricsRequest\"}[5m])/rate(kata_shim_agent_rpc_durations_histogram_milliseconds_count{action=\"grpc.GetMetricsRequest\"}[5m])",
     "legendFormat": "avg/{{action}}/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "kata_shim netdev",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_shim_netdev",
     "legendFormat": "{{interface}}/{{item}}/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_shim_go_goroutines", "legendFormat": "{{sandbox_id}}" }
   ]
  },
  {
   "title": "VmRSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_shim_proc_status{item=\"vmrss\"}",
     "legendFormat": "VmRSS/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "IO stats bytes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kata_shim_io_stat{item=\"rchar\"}[5m])",
     "legendFormat": "Read/{{sandbox_id}}"
    },
    {
     "expr": "irate(kata_shim_io_stat{item=\"wchar\"}[5m])",
     "legendFormat": "Write/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "shim open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_shim_fds", "legendFormat": "{{sandbox_id}}" }
   ]
  },
  {
   "title": "kata shim proc status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_shim_proc_status" }
   ]
  },
  {
   "title": "gc duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kata_shim_go_gc_duration_seconds_sum[5m])/rate(kata_shim_go_gc_duration_seconds_count[5m])"
    }
   ]
  },
  { "title": "Kata agent", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "kata_agent_process_open_fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_agent_process_open_fds" }
   ]
  },
  {
   "title": "agent mem/RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_agent_process_resident_memory_bytes",
     "legendFormat": "{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "agent proc status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_agent_proc_status" }
   ]
  },
  {
   "title": "agent proc status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_agent_proc_stat" }
   ]
  },
  { "title": "Hypervisor", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "hypervisor open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_hypervisor_fds", "legendFormat": "{{sandbox_id}}" }
   ]
  },
  {
   "title": "VmRSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_hypervisor_proc_status{item=\"vmrss\"}",
     "legendFormat": "{{item}}/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "IO WChar/RChar",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_hypervisor_io_stat{item=\"wchar\"}",
     "legendFormat": "{{item}}/{{sandbox_id}}"
    },
    {
     "expr": "kata_hypervisor_io_stat{item=\"rchar\"}",
     "legendFormat": "{{item}}/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "hypeervisor net",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_hypervisor_netdev",
     "legendFormat": "{{interface}}/{{item}}/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "proc stat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_hypervisor_proc_stat", "legendFormat": "{{item}}/{{sandbox_id}}" }
   ]
  },
  { "title": "Guest OS", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "guest load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_guest_load", "legendFormat": "{{item}}/{{sandbox_id}}" }
   ]
  },
  {
   "title": "meminfo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_guest_meminfo{item=\"mem_total\"}",
     "legendFormat": "{{item}}/{{sandbox_id}}"
    },
    {
     "expr": "kata_guest_meminfo{item=\"mem_free\"}",
     "legendFormat": "{{item}}/{{sandbox_id}}"
    },
    {
     "expr": "kata_guest_meminfo{item=\"mem_available\"}",
     "legendFormat": "{{item}}/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "netdev sent/recv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_guest_netdev_stat{item=\"sent_bytes\"}",
     "legendFormat": "{{item}}/{{interface}}/{{sandbox_id}}"
    },
    {
     "expr": "kata_guest_netdev_stat{item=\"recv_bytes\"}",
     "legendFormat": "{{item}}/{{interface}}/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "netdev errors/drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kata_guest_netdev_stat{item=\"sent_errs\"}",
     "legendFormat": "{{item}}/{{interface}}/{{sandbox_id}}"
    },
    {
     "expr": "kata_guest_netdev_stat{item=\"recv_errs\"}",
     "legendFormat": "{{item}}/{{interface}}/{{sandbox_id}}"
    },
    {
     "expr": "kata_guest_netdev_stat{item=\"sent_drop\"}",
     "legendFormat": "{{item}}/{{interface}}"
    },
    {
     "expr": "kata_guest_netdev_stat{item=\"recv_drop\"}",
     "legendFormat": "{{item}}/{{interface}}/{{sandbox_id}}"
    }
   ]
  },
  {
   "title": "tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kata_guest_tasks", "legendFormat": "{{item}}/{{sandbox_id}}" }
   ]
  }
 ]
}