
# nodeName: telecom-k8s-phy01


---
apiVersion: v1
kind: Pod
metadata:
  name: test-kata
spec:
  runtimeClassName: kata-containers
  containers:
  - name: fio
    image: docker.io/xridge/fio:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /test
      name: test-volume
    command:
    - sleep
    - "999d"
    resources:
      limits:
        memory: "2Gi"
        cpu: "2"
  volumes:
  - name: test-volume
    hostPath:
      path: /hff/test/kata
      type: Directory

---
apiVersion: v1
kind: Pod
metadata:
  name: test-runc
spec:
  containers:
  - name: fio
    image: docker.io/xridge/fio:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /test
      name: test-volume
    command:
    - sleep
    - "999d"
    resources:
      limits:
        memory: "2Gi"
        cpu: "2"
  volumes:
  - name: test-volume
    hostPath:
      path: /hff/test/runc
      type: Directory

---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-server
spec:
  containers:
  - image: sirot/netperf-latest
    command: ["/bin/sh","-c","netserver -p 4444 -4; iperf3 -s -i 1;"]
    imagePullPolicy: IfNotPresent
    name: netperf
    ports:
    - name: netperf-port
      containerPort: 4444
    - name: iperf-port
      containerPort: 5210
    resources:
      limits:
        memory: "5Gi"
        cpu: "5"


---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-server
spec:
  containers:
  - image: vish/stress
    imagePullPolicy: IfNotPresent
    name: stress
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        memory: "1000Mi"
        cpu: "2"
      limits:
        memory: "1000Mi"
        cpu: "2"
    args:
    - -cpus
    - "1"

